param(
    [switch]$SkipExeBuild
)

$ErrorActionPreference = "Stop"

$Root = Split-Path -Parent $MyInvocation.MyCommand.Path
$VenvPath = Join-Path $Root ".venv"
$Python = Join-Path $VenvPath "Scripts\python.exe"
# X-108: onedir -- the app payload is the whole folder, exe inside it.
$AppDir = Join-Path $Root "dist\Talk Dat!"
$AppExe = Join-Path $AppDir "Talk Dat!.exe"
$UninstallerExe = Join-Path $Root "dist\Talk Dat! Uninstaller.exe"
$InstallerExe = Join-Path $Root "dist\Talk Dat! Installer.exe"
$ReleaseDir = Join-Path $Root "release"
$ReleaseInstaller = Join-Path $ReleaseDir "Talk-Dat-Setup.exe"
$IconPath = Join-Path $Root "knight_flow\assets\app_icon.ico"
$BuildDir = Join-Path $Root "build"
$InstallerVersionInfo = Join-Path $BuildDir "talk-dat-installer-version-info.txt"
$BrandFontFile = Join-Path $Root "knight_flow\assets\fonts\KnightDisplay.ttf"
$UninstallerVersionInfo = Join-Path $BuildDir "talk-dat-uninstaller-version-info.txt"
$StartHereDoc = Join-Path $Root "docs\START_HERE_WINDOWS.md"
$InstallDoc = Join-Path $Root "docs\INSTALL.md"

$ProvidersDoc = Join-Path $Root "docs\PROVIDERS.md"
$ModelCatalogDoc = Join-Path $Root "docs\MODEL_CATALOG.md"
$LicenseDoc = Join-Path $Root "LICENSE"
$NoticeDoc = Join-Path $Root "NOTICE"
$EulaDoc = Join-Path $Root "EULA.md"
$ThirdPartyNoticesDoc = Join-Path $Root "THIRD_PARTY_NOTICES.md"
# Generated by build-exe.ps1 (scripts\collect_licenses.py) from the packages
# actually bundled; the installer refuses to build without it.
$ThirdPartyLicensesDoc = Join-Path $AppDir "THIRD_PARTY_LICENSES.txt"

function Test-UsablePython {
    param([string]$Path)
    if (-not (Test-Path $Path)) { return $false }
    try {
        & $Path --version *> $null
        if ($LASTEXITCODE -ne 0) { return $false }
        & $Path -m pip --version *> $null
        return $LASTEXITCODE -eq 0
    } catch {
        return $false
    }
}

function Invoke-Checked {
    param(
        [string]$Label,
        [scriptblock]$Script
    )
    & $Script
    if ($LASTEXITCODE -ne 0) {
        throw "$Label failed with exit code $LASTEXITCODE"
    }
}

function New-VersionInfoFile {
    param(
        [string]$Path,
        [string]$Version,
        [string]$FileDescription,
        [string]$OriginalFilename
    )
    $VersionParts = [regex]::Matches($Version, "\d+") | ForEach-Object { [int]$_.Value }
    $Numbers = @(0, 0, 0, 0)
    for ($Index = 0; $Index -lt [Math]::Min(4, $VersionParts.Count); $Index++) {
        $Numbers[$Index] = $VersionParts[$Index]
    }
    $NumericVersion = "$($Numbers[0]).$($Numbers[1]).$($Numbers[2]).$($Numbers[3])"
    $Text = @"
# UTF-8
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers=($($Numbers[0]), $($Numbers[1]), $($Numbers[2]), $($Numbers[3])),
    prodvers=($($Numbers[0]), $($Numbers[1]), $($Numbers[2]), $($Numbers[3])),
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0)
  ),
  kids=[
    StringFileInfo([
      StringTable('040904b0', [
        StringStruct('CompanyName', 'Knight AI+AV'),
        StringStruct('FileDescription', '$FileDescription'),
        StringStruct('FileVersion', '$NumericVersion'),
        StringStruct('InternalName', 'Talk Dat!'),
        StringStruct('OriginalFilename', '$OriginalFilename'),
        StringStruct('ProductName', 'Talk Dat!'),
        StringStruct('ProductVersion', '$Version')
      ])
    ]),
    VarFileInfo([VarStruct('Translation', [1033, 1200])])
  ]
)
"@
    New-Item -ItemType Directory -Force -Path (Split-Path -Parent $Path) | Out-Null
    Set-Content -LiteralPath $Path -Value $Text -Encoding UTF8
}

$BuildMutex = [System.Threading.Mutex]::new($false, "Local\TalkDatCustomInstallerBuild")
$HasBuildMutex = $false

try {
    try {
        $HasBuildMutex = $BuildMutex.WaitOne(0)
    } catch [System.Threading.AbandonedMutexException] {
        $HasBuildMutex = $true
    }

    if (-not $HasBuildMutex) {
        throw "Another Talk Dat! installer build is already running. Wait for it to finish before starting a new build."
    }

# A running instance of the BUILD PAYLOAD locks PyInstaller's output. Match
# its exact executable path so preparing a release never interrupts the
# installed app. Own the build mutex before stopping or deleting anything.
if (-not $SkipExeBuild) {
    $ResolvedRoot = (Resolve-Path -LiteralPath $Root).Path.TrimEnd('\')
    $ResolvedAppDir = [IO.Path]::GetFullPath($AppDir)
    $ExpectedAppDir = Join-Path $ResolvedRoot 'dist\Talk Dat!'
    if (-not [string]::Equals($ResolvedAppDir, $ExpectedAppDir, [StringComparison]::OrdinalIgnoreCase)) {
        throw "Refusing to clean a build payload outside this repository: $ResolvedAppDir"
    }
    foreach ($PayloadPath in @((Join-Path $ResolvedRoot 'dist'), $ResolvedAppDir)) {
        if ((Test-Path -LiteralPath $PayloadPath) -and
            ((Get-Item -LiteralPath $PayloadPath).Attributes -band [IO.FileAttributes]::ReparsePoint)) {
            throw "Refusing to clean a linked build directory: $PayloadPath"
        }
    }
    $ResolvedAppExe = Join-Path $ResolvedAppDir 'Talk Dat!.exe'
    Get-Process "Talk Dat!" -ErrorAction SilentlyContinue |
        Where-Object { $_.Path -and [string]::Equals($_.Path, $ResolvedAppExe, [StringComparison]::OrdinalIgnoreCase) } |
        Stop-Process -Force -ErrorAction SilentlyContinue
    Start-Sleep -Seconds 2
    if (Test-Path -LiteralPath $ResolvedAppDir) {
        Remove-Item -LiteralPath $ResolvedAppDir -Recurse -Force
    }
}
# End build-payload cleanup

if (-not (Test-UsablePython $Python)) {
    if (Test-Path $VenvPath) {
        $ResolvedRoot = (Resolve-Path $Root).Path
        $ResolvedVenv = (Resolve-Path $VenvPath).Path
        if (-not $ResolvedVenv.StartsWith($ResolvedRoot, [System.StringComparison]::OrdinalIgnoreCase)) {
            throw "Refusing to remove virtualenv outside repo: $ResolvedVenv"
        }
        Remove-Item -LiteralPath $ResolvedVenv -Recurse -Force
    }
    $Uv = Get-Command uv -ErrorAction SilentlyContinue
    if ($Uv) {
        if (-not $env:UV_CACHE_DIR) {
            $env:UV_CACHE_DIR = Join-Path $Root ".uv-cache"
        }
        if (-not $env:UV_PYTHON_INSTALL_DIR) {
            $env:UV_PYTHON_INSTALL_DIR = Join-Path $Root ".uv-python"
        }
        Invoke-Checked "uv venv" { & $Uv.Source venv --seed $VenvPath }
    } else {
        Invoke-Checked "python venv" { python -m venv $VenvPath }
    }
}

if (-not (Test-UsablePython $Python)) {
    throw "Could not create a usable Python virtualenv at $VenvPath"
}

Invoke-Checked "pip upgrade" { & $Python -m pip install --upgrade pip }
# X-230: install from the LOCK, not the ranges.
#
# requirements.txt is entirely ranges: websockets>=14.0, numpy>=1.26, and so
# on, with no upper bound on most and no pin on any transitive dependency. So
# every build of the SIGNED binary pulled whatever PyPI happened to serve that
# minute, and two builds of the same commit could contain different code. A
# compromised or merely broken upstream release would land inside a binary
# carrying Knight AI+AV's Authenticode signature, which is the strongest claim
# this project makes about a file.
#
# requirements.lock pins every package, direct and transitive, to an exact
# version AND a set of SHA-256 hashes. pip verifies each hash before it
# installs, so a substituted artifact fails the build instead of shipping.
#
# Regenerate deliberately, never casually:
#     uv pip compile requirements.txt --generate-hashes --output-file requirements.lock
# X-408: --no-deps, because the lock is the complete transitive set already and the
# resolver would otherwise insist on the CPU onnxruntime that faster-whisper and
# openwakeword name, which the lock excludes on Windows in favour of DirectML.
Invoke-Checked "requirements install" { & $Python -m pip install --require-hashes --no-deps -r (Join-Path $Root "requirements.lock") }
# X-408: the DirectML build of onnxruntime must be the one that lands. faster-whisper
# and openwakeword ask for plain onnxruntime, so the lock carries both wheels and
# they overwrite each other's files in whatever order pip chose. Reinstalling the
# DirectML wheel last, without its dependencies, settles it; the check after it
# fails the build rather than shipping a CPU-only runtime by accident.
$DirectMlPin = (Get-Content (Join-Path $Root "requirements.lock")) | Where-Object { $_ -match "^onnxruntime-directml==" } | ForEach-Object { ($_ -split "\s")[0] } | Select-Object -First 1
if (-not $DirectMlPin) { throw "requirements.lock has no onnxruntime-directml pin" }
Invoke-Checked "directml runtime" { & $Python -m pip install --force-reinstall --no-deps $DirectMlPin }
Invoke-Checked "directml present" { & $Python -c "import onnxruntime as o, sys; sys.exit(0 if 'DmlExecutionProvider' in o.get_available_providers() else 1)" }
Invoke-Checked "pyinstaller install" { & $Python -m pip install pyinstaller }

if (-not (Test-Path $IconPath)) {
    $IconPath = (& $Python -c "from knight_flow.icon import ensure_icon_file; print(ensure_icon_file())").Trim()
}

$AppVersion = (& $Python -c "from knight_flow.version import APP_VERSION; print(APP_VERSION)").Trim()
New-VersionInfoFile -Path $UninstallerVersionInfo -Version $AppVersion -FileDescription "Talk Dat! uninstaller" -OriginalFilename "Talk Dat! Uninstaller.exe"
New-VersionInfoFile -Path $InstallerVersionInfo -Version $AppVersion -FileDescription "Talk Dat! installer" -OriginalFilename "Talk Dat! Installer.exe"

if (-not $SkipExeBuild) {
    Invoke-Checked "app exe build" { & (Join-Path $Root "build-exe.ps1") }
}

if (-not (Test-Path $AppExe)) {
    throw "Missing app EXE. Run .\build-exe.ps1 first, or omit -SkipExeBuild."
}

New-Item -ItemType Directory -Force -Path $ReleaseDir | Out-Null

$CommonArgs = @(
    "-m", "PyInstaller",
    "--noconfirm",
    "--clean",
    "--onefile",
    "--windowed",
    "--icon", "$IconPath",
    # X-118: the branded card appears the instant the exe runs, DURING the
    # onefile extraction -- the tester clicked three times before the old
    # window finally painted. glass_installer closes it once Tk is up.
    "--splash", "installer\splash.png",
    "--hidden-import", "PIL._tkinter_finder",
    # The installer UI is a small Tk app and has no business carrying a
    # numerical stack. Excluded here as well as in build-exe.ps1 so a stray
    # transitive import cannot quietly put 148 MB back.
    "--exclude-module", "scipy",
    "--exclude-module", "sklearn",
    "--exclude-module", "scikit-learn",
    # Defensive, not a saving. cv2 is 109 MB in the virtualenv and arrives
    # through pyautogui -> pyscreeze for locateOnScreen image matching, which
    # this product never performs. Excluding it was measured and changed the
    # executable by exactly 0 MB: PyInstaller's analysis was already leaving it
    # out. Kept so a future dependency cannot quietly pull it back in, and so
    # the next person does not repeat the measurement.
    "--exclude-module", "cv2",
    # X-476: the CUDA wheels are 1.2 GB and help only NVIDIA machines.
    # The runtime fetches them on request; nothing bundles them.
    "--exclude-module", "nvidia",
    # Open source (2026-09-23): pyautogui's optional helpers. The app uses
    # pyautogui for key presses only; pyautogui imports each of these inside
    # try/except ImportError. mouseinfo is GPL-3.0-or-later and pymsgbox is
    # classified GPLv3+, so neither may ride along in a binary by accident.
    # Kept identical to the excludes in "Talk Dat!.spec".
    "--exclude-module", "mouseinfo",
    "--exclude-module", "pymsgbox",
    "--exclude-module", "pyscreeze",
    "--exclude-module", "pygetwindow",
    "--exclude-module", "pyrect"
)

$AssetAdds = @(
    @((Join-Path $Root "knight_flow\assets\app_icon.ico"), "knight_flow/assets"),
    @((Join-Path $Root "knight_flow\assets\app_icon.png"), "knight_flow/assets"),
    @((Join-Path $Root "knight_flow\assets\logo.png"), "knight_flow/assets"),
    @((Join-Path $Root "knight_flow\assets\flow_pill_240.png"), "knight_flow/assets"),
    @((Join-Path $Root "knight_flow\assets\flow_pill_240.json"), "knight_flow/assets"),
    @((Join-Path $Root "knight_flow\assets\ui\installer-clay.jpg"), "knight_flow/assets/ui")
)

$UninstallerArgs = @()
$UninstallerArgs += $CommonArgs
foreach ($AssetAdd in $AssetAdds) {
    if (Test-Path $AssetAdd[0]) {
        $UninstallerArgs += @("--add-data", "$($AssetAdd[0]);$($AssetAdd[1])")
    }
}
$UninstallerArgs += @(
    "--version-file", "$UninstallerVersionInfo",
    "--name", "Talk Dat! Uninstaller",
    (Join-Path $Root "installer\uninstall_entry.py")
)

Invoke-Checked "uninstaller build" { & $Python $UninstallerArgs }

if (-not (Test-Path $UninstallerExe)) {
    throw "Custom uninstaller build failed."
}

# Signing is opt-in for a build from source (2026-09-23, open source). An
# OFFICIAL build (build\talk-dat-build-flags.json, written by build-exe.ps1)
# signs exactly as before and fails closed without credentials. A SOURCE build
# passes --if-configured: with no credentials on the machine it prints a clear
# "building UNSIGNED" message and carries on. publish_release.py still signs
# every release artifact itself and still fails closed.
$BuildKind = (& $Python (Join-Path $Root "scripts\write_build_flags.py") --show | Out-String).Trim()
$SignArgs = @()
if ($BuildKind -ne "official") {
    $SignArgs = @("--if-configured")
    Write-Output "Source build: signing only if this machine has signing credentials."
}

if (-not (Test-Path -LiteralPath $ThirdPartyLicensesDoc -PathType Leaf)) {
    throw "Missing $ThirdPartyLicensesDoc. Run .\build-exe.ps1 (it generates the third-party license bundle)."
}

# Sign before embedding: signing the outside installer at publish time cannot
# change the app and uninstaller already sealed inside its payload.
Invoke-Checked "payload signing" { & $Python (Join-Path $Root "scripts\sign_windows.py") @SignArgs $AppExe $UninstallerExe }

$InstallerArgs = @()
$InstallerArgs += $CommonArgs
foreach ($AssetAdd in $AssetAdds) {
    if (Test-Path $AssetAdd[0]) {
        $InstallerArgs += @("--add-data", "$($AssetAdd[0]);$($AssetAdd[1])")
    }
}
$InstallerArgs += @(
    "--add-data", "$AppDir;payload/app",
    "--add-data", "$UninstallerExe;payload",
    "--add-data", "$StartHereDoc;payload/docs",
    "--add-data", "$InstallDoc;payload/docs",
    "--add-data", "$ProvidersDoc;payload/docs",
    "--add-data", "$ModelCatalogDoc;payload/docs",
    "--add-data", "$LicenseDoc;payload/docs",
    "--add-data", "$NoticeDoc;payload/docs",
    "--add-data", "$EulaDoc;payload/docs",
    "--add-data", "$ThirdPartyNoticesDoc;payload/docs",
    "--add-data", "$ThirdPartyLicensesDoc;payload/docs",
    "--add-data", "$BrandFontFile;payload/fonts",
    "--version-file", "$InstallerVersionInfo",
    "--name", "Talk Dat! Installer",
    (Join-Path $Root "installer\install_entry.py")
)

Invoke-Checked "installer build" { & $Python $InstallerArgs }

if (-not (Test-Path $InstallerExe)) {
    throw "Custom installer build failed."
}

Invoke-Checked "installer signing" { & $Python (Join-Path $Root "scripts\sign_windows.py") @SignArgs $InstallerExe }

Copy-Item $InstallerExe $ReleaseInstaller -Force

Write-Output "Custom installer output:"
Write-Output $ReleaseInstaller
} finally {
    if ($HasBuildMutex) {
        $BuildMutex.ReleaseMutex()
    }
    $BuildMutex.Dispose()
}
