"""Find-more P0-5: the Mac pasteboard, borrowed for a dictation and given back whole.

On the Mac every dictation destroyed a copied image, file or formatted text:
the paste layer saved the old clipboard as plain text (pyperclip), which is ""
for an image or a file, and wrote that text back after Command+V. The borrowed
write carried none of the nspasteboard.org markers, so Maccy, Raycast, Paste
and their kind kept every dictation, and Universal Clipboard offered it to the
person's other Apple devices. The Windows fixes for the same things (X-406's
snapshot, X-604's private formats) never reached this branch.

This module is the Mac's half of those fixes, driven by knight_flow/paste.py:

- a snapshot of EVERY type of EVERY pasteboard item, read before the paste;
- Talk DAT!'s own writes cleared with the current-host-only option (never
  Universal Clipboard) and, when borrowed, marked TransientType (and
  ConcealedType for a password take), so clipboard managers skip them;
- the pasteboard's changeCount as the ownership token: the old clipboard is
  put back only while the count is still the one our own write left;
- the late-reader fix (the Mac form of P0-4 / X-665's delayed rendering): the
  borrowed dictation is a promise, an NSPasteboardItem data provider, so the
  moment the target reads is known. The paste waits for that read, gives the
  old clipboard back READ_GRACE_S after it, and past READ_CEILING_S leaves the
  dictation on the pasteboard instead of guessing.

Import-safe everywhere: AppKit and objc are imported inside functions, and the
decisions (`is_plain_text`, `classify_read`) are pure, so the suite checks them
on Windows against a fake pasteboard (tests/mac_pasteboard_fake.py).

The data provider is called by AppKit on the main thread (the Tk/AppKit run
loop). A paste waiting there for its own read would wait for itself, so a
promise is only offered from another thread (dictations deliver on the speech
thread); on the main thread the dictation is written as plain data, and the
restore falls back to the old fixed delay.
"""
from __future__ import annotations

import collections
import logging
import os
import threading
import time
from contextlib import contextmanager
from dataclasses import dataclass
from typing import Any

log = logging.getLogger(__name__)

PLAIN_TEXT_TYPE = "public.utf8-plain-text"
#: nspasteboard.org: "gone in a moment, do not record it" and "a secret".
TRANSIENT_TYPE = "org.nspasteboard.TransientType"
CONCEALED_TYPE = "org.nspasteboard.ConcealedType"
#: Types that describe a copy rather than carry it; losing them loses nothing.
MARKER_TYPES = frozenset({
    TRANSIENT_TYPE, CONCEALED_TYPE, "org.nspasteboard.AutoGeneratedType", "org.nspasteboard.source",
})
#: A pasteboard holding only these (one item) is plain text, and putting plain
#: text back over it loses nothing. Anything else is an image, a file, or
#: formatting, and plain text written over it destroys it.
PLAIN_TEXT_TYPES = frozenset({
    PLAIN_TEXT_TYPE, "public.utf16-plain-text", "public.utf16-external-plain-text", "public.plain-text",
    "public.text", "NSStringPboardType", "com.apple.traditional-mac-plain-text",
})

#: How long a paste waits for the target to read. Past this the dictation stays:
#: a missed restore costs the person their old clipboard, a restore before the
#: read pastes the old clipboard into their document. Windows uses the same 2 s.
READ_CEILING_S = 2.0
#: After the read, before the restore: an app may come back for a second type,
#: and the old fixed delay was 0.2 s after the chord, so this is never sooner.
READ_GRACE_S = 0.2
#: Same bound as the Windows snapshot (paste._SNAPSHOT_MAX_BYTES).
MAX_SNAPSHOT_BYTES = 64 * 1024 * 1024
#: Find-more P1-4: Fix That and Command mode now paste in place on the Mac and
#: put the old clipboard back as soon as the paste layer returns, 10 ms after
#: Command+V. An app that reads later would paste the old clipboard, so a
#: plain-text restore waits until this long after our last write: the same
#: floor the dictation paste always had.
RESTORE_SETTLE_S = 0.2

_TAKE = threading.local()
_LAST_WRITE_AT = 0.0
_PROVIDER_CLASS: Any = None
# The pasteboard holds the item; nothing documents that it holds the item's
# data provider, and a provider collected while a reader asks for its data
# would crash AppKit. The last few borrows are kept alive here.
_LIVE: collections.deque = collections.deque(maxlen=4)


# -- pure decisions --------------------------------------------------------------
def is_plain_text(item_types: list[list[str]]) -> bool:
    """Whether putting plain text back over this pasteboard loses nothing."""
    if len(item_types) > 1:
        return False
    return all(kind in PLAIN_TEXT_TYPES or kind in MARKER_TYPES for kinds in item_types for kind in kinds)


def classify_read(first_read_at: float | None, chord_at: float, lost: bool) -> str | None:
    """"read" (the target took the dictation after the chord), "early" (someone
    read before the chord, so the target's read will be silent), "lost"
    (another app replaced the pasteboard), or None: keep waiting."""
    if first_read_at is not None:
        return "early" if first_read_at < chord_at else "read"
    if lost:
        return "lost"
    return None


def markers(*, transient: bool, concealed: bool) -> list[str]:
    if concealed:
        return [TRANSIENT_TYPE, CONCEALED_TYPE]
    return [TRANSIENT_TYPE] if transient else []


@contextmanager
def concealed_writes(concealed: bool = True):
    """Every write made on this thread inside the block is a secret (a password take)."""
    previous = bool(getattr(_TAKE, "concealed", False))
    _TAKE.concealed = bool(concealed)
    try:
        yield
    finally:
        _TAKE.concealed = previous


def writes_are_concealed() -> bool:
    return bool(getattr(_TAKE, "concealed", False))


def native() -> bool:
    """Whether the pasteboard is used directly.

    TALK_DAT_PLAIN_CLIPBOARD=1 (X-604's switch, set for the whole test
    package so no test can reach the person's real clipboard) turns every
    part of this module off, and the paste layer behaves as it did before
    P0-5: pyperclip, plain text, no ownership token.
    """
    return os.environ.get("TALK_DAT_PLAIN_CLIPBOARD") != "1"


def settle_remaining(now: float | None = None) -> float:
    """Seconds still to wait before a restore may replace Talk DAT!'s last write."""
    now = time.monotonic() if now is None else now
    return max(0.0, RESTORE_SETTLE_S - (now - _LAST_WRITE_AT))


def _noted_write() -> None:
    global _LAST_WRITE_AT
    _LAST_WRITE_AT = time.monotonic()


# -- AppKit glue (thin; proven on the Mac, faked on Windows) -----------------------
def _appkit() -> Any:
    import AppKit

    return AppKit


def _pasteboard() -> Any:
    return _appkit().NSPasteboard.generalPasteboard()


def _clear_for_writing(pasteboard: Any, appkit: Any) -> int:
    """Empty the pasteboard for a write that stays on this Mac. Returns the new count.

    prepareForNewContentsWithOptions: exists from macOS 10.12, the release that
    brought Universal Clipboard, so where it is missing there is nothing to
    keep the words away from.
    """
    option = getattr(appkit, "NSPasteboardContentsCurrentHostOnly", None)
    prepare = getattr(pasteboard, "prepareForNewContentsWithOptions_", None)
    if option is not None and prepare is not None:
        return int(prepare(option) or 0)
    return int(pasteboard.clearContents() or 0)


def _empty_data(appkit: Any) -> Any:
    return appkit.NSData.dataWithBytes_length_(b"", 0)


def change_count() -> int:
    """The pasteboard's generation, or 0 when it cannot be read (never a usable token)."""
    try:
        return int(_pasteboard().changeCount())
    except Exception:
        log.debug("pasteboard changeCount unavailable", exc_info=True)
        return 0


def item_types() -> list[list[str]] | None:
    """The types of every item, read without asking anyone for data (no promise fires)."""
    try:
        items = _pasteboard().pasteboardItems() or ()
        return [[str(kind) for kind in (item.types() or ())] for item in items]
    except Exception:
        log.debug("pasteboard types unavailable", exc_info=True)
        return None


def write_text(text: str, *, transient: bool, concealed: bool | None = None) -> bool:
    """Talk DAT!'s own copy: kept on this Mac, and marked when it is only borrowed.

    X-604 on Windows keeps every copy off the cloud clipboard and a borrowed
    one out of clipboard history; this is the same promise on the Mac.
    """
    concealed = writes_are_concealed() if concealed is None else concealed
    appkit = _appkit()
    pasteboard = _pasteboard()
    item = appkit.NSPasteboardItem.alloc().init()
    if not item.setString_forType_(text, PLAIN_TEXT_TYPE):
        return False
    for marker in markers(transient=transient, concealed=concealed):
        item.setData_forType_(_empty_data(appkit), marker)
    _clear_for_writing(pasteboard, appkit)
    written = bool(pasteboard.writeObjects_([item]))
    _noted_write()
    return written


def restore_text(previous: str, token: int) -> int:
    """Put plain text back over the generation `token`. Returns the new count, or 0.

    An empty `previous` was an empty pasteboard (the probe routes anything
    richer to the snapshot), so it comes back empty, not as "".
    """
    appkit = _appkit()
    pasteboard = _pasteboard()
    if not token or int(pasteboard.changeCount()) != int(token):
        return 0
    items = []
    if previous:
        item = appkit.NSPasteboardItem.alloc().init()
        item.setString_forType_(previous, PLAIN_TEXT_TYPE)
        # X-604: the restore is not a new copy for anyone's history.
        item.setData_forType_(_empty_data(appkit), TRANSIENT_TYPE)
        items.append(item)
    _clear_for_writing(pasteboard, appkit)
    if items and not pasteboard.writeObjects_(items):
        return 0
    return int(pasteboard.changeCount())


@dataclass(frozen=True)
class PasteboardSnapshot:
    """Every type of every item, and the generation it was read from.

    Always truthy: an empty pasteboard is a faithful snapshot too.
    """

    items: tuple[tuple[tuple[str, bytes], ...], ...]
    change_count: int


def take_snapshot() -> PasteboardSnapshot | None:
    """Read everything on the pasteboard, or None when it cannot be kept faithfully.

    None sends the paste to typing, as on Windows: a type with no data (a
    promise its owner will not keep), more than MAX_SNAPSHOT_BYTES, or a
    pasteboard that changed while it was being read.
    """
    try:
        pasteboard = _pasteboard()
        count = int(pasteboard.changeCount())
        total = 0
        items = []
        for item in pasteboard.pasteboardItems() or ():
            kept = []
            for kind in item.types() or ():
                data = item.dataForType_(kind)
                if data is None:
                    log.info("pasteboard type %s has no data; the paste will type instead", kind)
                    return None
                payload = bytes(data)
                total += len(payload)
                if total > MAX_SNAPSHOT_BYTES:
                    log.info("pasteboard holds over %d MB; the paste will type instead", MAX_SNAPSHOT_BYTES >> 20)
                    return None
                kept.append((str(kind), payload))
            items.append(tuple(kept))
        if int(pasteboard.changeCount()) != count:
            return None
        return PasteboardSnapshot(tuple(items), count)
    except Exception:
        log.debug("pasteboard snapshot failed; the paste will type instead", exc_info=True)
        return None


def restore_snapshot(snapshot: PasteboardSnapshot, token: int) -> bool:
    """Put every item back, only while the pasteboard is still at generation `token`."""
    appkit = _appkit()
    pasteboard = _pasteboard()
    if not token or int(pasteboard.changeCount()) != int(token):
        return False
    items = []
    for pairs in snapshot.items:
        item = appkit.NSPasteboardItem.alloc().init()
        for kind, payload in pairs:
            item.setData_forType_(appkit.NSData.dataWithBytes_length_(payload, len(payload)), kind)
        if TRANSIENT_TYPE not in {kind for kind, _ in pairs}:
            # X-604: what the person had is put back, not copied again, so a
            # clipboard manager does not list it twice.
            item.setData_forType_(_empty_data(appkit), TRANSIENT_TYPE)
        items.append(item)
    # Current host only: a password manager's copy would otherwise be offered
    # to the person's other devices by the restore, which it may never have been.
    _clear_for_writing(pasteboard, appkit)
    return bool(pasteboard.writeObjects_(items)) if items else True


# -- the borrowed dictation, as a promise -------------------------------------------
def _provider_class() -> Any:
    """The Objective-C data provider. Defined once: the runtime registers classes by name."""
    global _PROVIDER_CLASS
    if _PROVIDER_CLASS is not None:
        return _PROVIDER_CLASS
    appkit = _appkit()
    import objc

    try:
        protocols = [objc.protocolNamed("NSPasteboardItemDataProvider")]
    except Exception:
        protocols = []

    class TalkDatPasteboardPromise(appkit.NSObject, protocols=protocols):
        @objc.python_method
        def bind(self, owner) -> None:
            self._owner = owner

        def pasteboard_item_provideDataForType_(self, _pasteboard, item, kind) -> None:  # noqa: N802
            # An exception escaping into AppKit would take the app down.
            try:
                owner = getattr(self, "_owner", None)
                if owner is not None:
                    owner._provide(item, str(kind))
            except Exception:
                log.warning("pasteboard promise could not be kept", exc_info=True)

        def pasteboardFinishedWithDataProvider_(self, _pasteboard) -> None:  # noqa: N802
            try:
                owner = getattr(self, "_owner", None)
                if owner is not None:
                    owner._finished_with()
            except Exception:
                log.debug("pasteboard promise release failed", exc_info=True)

    _PROVIDER_CLASS = TalkDatPasteboardPromise
    return _PROVIDER_CLASS


class BorrowedPasteboard:
    """One dictation on the pasteboard as a promise, so its reader can be seen.

    The same shape as the Windows owner on main (clipboard_owner.BorrowedClipboard):
    `wait_for_read`, `rendered_sequence`, `keep`, so the paste layer drives both
    the same way. The provider side does the least it can (hand the text over,
    note when, wake the waiter) and never takes the paste layer's lock, which
    the waiting paste holds.
    """

    def __init__(self, text: str, *, concealed: bool) -> None:
        self._text: str | None = text
        self._concealed = bool(concealed)
        self._lock = threading.Lock()
        self._read_event = threading.Event()
        self._finished = threading.Event()
        self._rendering = False
        self._reads: list[float] = []
        self._provider: Any = None
        self._item: Any = None
        self.token = 0
        self.rendered_sequence = 0

    def offer(self) -> int:
        """Put the promise on the pasteboard. Returns the changeCount after the write, or 0."""
        appkit = _appkit()
        pasteboard = _pasteboard()
        provider = _provider_class().alloc().init()
        provider.bind(self)
        item = appkit.NSPasteboardItem.alloc().init()
        if not item.setDataProvider_forTypes_(provider, [PLAIN_TEXT_TYPE]):
            return 0
        for marker in markers(transient=True, concealed=self._concealed):
            item.setData_forType_(_empty_data(appkit), marker)
        self._provider, self._item = provider, item
        _LIVE.append(self)
        _clear_for_writing(pasteboard, appkit)
        if not pasteboard.writeObjects_([item]):
            return 0
        _noted_write()
        self.token = int(pasteboard.changeCount())
        return self.token

    # -- AppKit's side (main thread) ---------------------------------------------
    def _provide(self, item: Any, kind: str) -> None:
        with self._lock:
            text = self._text
            self._rendering = True
        try:
            if text is None:
                return
            item.setString_forType_(text, kind)
            rendered = change_count()
            with self._lock:
                self._text = None  # handed over; the data is the pasteboard's now
                self.rendered_sequence = rendered
                self._reads.append(time.perf_counter())
            self._read_event.set()
        finally:
            with self._lock:
                self._rendering = False

    def _finished_with(self) -> None:
        self._finished.set()
        self._read_event.set()

    # -- the paste's side -------------------------------------------------------------
    def _replaced(self) -> bool:
        count = change_count()
        return bool(count and self.token and count != self.token)

    def wait_for_read(self, chord_at: float, target_pid: int = 0, ceiling: float | None = None) -> str:
        """"read", "early", "lost" or "none" (nobody read before the ceiling).

        `target_pid` is unused: a Mac data provider is not told who reads. A
        reader before the chord is still recognised ("early").
        """
        del target_pid
        ceiling = READ_CEILING_S if ceiling is None else ceiling
        deadline = time.perf_counter() + max(0.0, ceiling)
        while True:
            with self._lock:
                first = self._reads[0] if self._reads else None
                rendering = self._rendering
            lost = first is None and not rendering and (self._finished.is_set() or self._replaced())
            outcome = classify_read(first, chord_at, lost)
            if outcome is not None:
                return outcome
            remaining = deadline - time.perf_counter()
            if remaining <= 0:
                return "none"
            self._read_event.wait(min(remaining, 0.05))

    def keep(self) -> bool:
        """Past the ceiling: turn the promise into real data and leave it there.

        A promise lives only as long as this process; the words must not.
        """
        with self._lock:
            pending = self._text
        if pending is None:
            return True
        if change_count() != self.token:
            return False  # another app's copy is there now; it is theirs
        if not write_text(pending, transient=True, concealed=self._concealed):
            return False
        with self._lock:
            self._text = None
        return True


def borrow(text: str, *, concealed: bool | None = None) -> BorrowedPasteboard | None:
    """Offer `text` as a promise, or None (the caller then writes it the ordinary way)."""
    if not native():
        return None
    if threading.current_thread() is threading.main_thread():
        # AppKit asks the provider on this thread; waiting here for the read
        # would wait for ourselves until the ceiling, and the target with us.
        return None
    concealed = writes_are_concealed() if concealed is None else concealed
    try:
        owner = BorrowedPasteboard(text, concealed=concealed)
        return owner if owner.offer() else None
    except Exception:
        log.warning("pasteboard promise unavailable; copying the ordinary way", exc_info=True)
        return None
