"""Settings theme families and palettes.

Pure data, split out of overlay.py so tools and tests can read it without importing
tkinter. overlay.py re-exports these names.

Families are ordered by material and temperature -- plaster and stone, earth, warm,
cool, neutral, neon -- rather than by the order they happened to be added. The
picker reads top to bottom, so related themes should sit together.
"""

from __future__ import annotations


SETTINGS_THEME_FAMILIES = (
    # Signature
    "Flow",
    # Plaster and stone
    "Roman Clay",
    "Venetian Plaster",
    "Lime Wash",
    "Sandstone",
    "Slate Quarry",
    # Earth
    "Deep Forest",
    "Oxide Copper",
    "Desert Bloom",
    # Warm
    "Ember Glass",
    "Solar Ribbon",
    "Crimson Bloom",
    "Champagne Glass",
    # Cool
    "Teal Circuit",
    "Aqua Noir",
    "Arctic Aurora",
    "Cobalt Heat",
    # Neutral and mono
    "Graphite Pulse",
    "Ivory Halo",
    "Midnight Ink",
    "Obsidian Gold",
    # Neon
    "Violet Signal",
    "Night City Neon",
    "Neon Sakura",
    "Terminal Rain",
    # X-538: ported from D-REC's colorways. Only bg, panel, text and accent
    # cross over; the other nine roles are derived and then MEASURED against
    # every gate in the suite before being written down. Four of those gates
    # were found by failing them, and each one passed a cheaper check first:
    #
    #   * the focus border is measured against `button` as well as `panel`,
    #     and `button` is the darker of the two in a light theme;
    #   * success, warning and danger are FIXED hexes _settings_palette writes
    #     over the theme, so they constrain how light a dark theme's surfaces
    #     may get rather than being a colour the palette chooses;
    #   * on_accent is black or white, so an accent may not sit mid-luminance;
    #   * the gallery row's MATERIAL is `select` blended toward `accent`, and
    #     a select that reads perfectly well itself can still land that
    #     material on a mid-tone nothing reads on. Olive Grove Dark did,
    #     at 4.36:1.
    #
    # Appended in group order: the groups must tile the families exactly once
    # IN ORDER, and the gallery grid is five columns wide.
    "Amber Lantern",
    "Brass Lamp",
    "Fire Opal",
    "Sunset Coast",
    "Rust Belt",
    "Bone China",
    "Paper Press",
    "Moss Stone",
    "Olive Grove",
    "Jade Garden",
    "Rose Quartz",
    "Emerald Vault",
    "Neon Wire",
    "Ultraviolet Hour",
    "Plum Velvet",
)

# X-458: the groups the Colors tab draws its tiles in. Every family sits in
# exactly one group, in the order of SETTINGS_THEME_FAMILIES.
SETTINGS_THEME_GROUPS = (
    ("Signature", ("Flow",)),
    ("Plaster and stone", ("Roman Clay", "Venetian Plaster", "Lime Wash", "Sandstone", "Slate Quarry")),
    ("Earth", ("Deep Forest", "Oxide Copper", "Desert Bloom")),
    ("Warm", ("Ember Glass", "Solar Ribbon", "Crimson Bloom", "Champagne Glass")),
    ("Cool", ("Teal Circuit", "Aqua Noir", "Arctic Aurora", "Cobalt Heat")),
    ("Neutral and mono", ("Graphite Pulse", "Ivory Halo", "Midnight Ink", "Obsidian Gold")),
    ("Neon", ("Violet Signal", "Night City Neon", "Neon Sakura", "Terminal Rain")),
    ("Metal and ember", ("Amber Lantern", "Brass Lamp", "Fire Opal", "Sunset Coast", "Rust Belt")),
    ("Garden and stone", ("Bone China", "Paper Press", "Moss Stone", "Olive Grove", "Jade Garden")),
    ("Signal", ("Rose Quartz", "Emerald Vault", "Neon Wire", "Ultraviolet Hour", "Plum Velvet")),
)

# X-767 (IP audit, 2026-09-24): the names people SEE for two families whose
# stored name borrowed someone else's. "Night City" is the city of CD PROJEKT's
# Cyberpunk games (and the palette is that franchise's yellow, cyan and pink);
# "Champagne" is a protected designation of origin. The stored name stays the
# key everywhere -- saved settings, material file names, the site-theme map --
# so every saved choice still loads; only the words on screen change.
SETTINGS_THEME_DISPLAY_NAMES = {
    "Night City Neon": "Yellow Neon",
    "Champagne Glass": "Pale Gold Glass",
}


def theme_display_name(name: str) -> str:
    """The name to show for a stored family or theme ("Night City Neon Dark"
    reads "Yellow Neon Dark"); every other name is its own display name."""
    text = str(name or "")
    for stored, shown in SETTINGS_THEME_DISPLAY_NAMES.items():
        if text == stored or text.startswith(stored + " "):
            return shown + text[len(stored):]
    return text


def theme_stored_name(name: str) -> str:
    """The stored name for a displayed family or theme; the inverse of
    theme_display_name, and the identity for a name that is already stored."""
    text = str(name or "")
    for stored, shown in SETTINGS_THEME_DISPLAY_NAMES.items():
        if text == shown or text.startswith(shown + " "):
            return stored + text[len(shown):]
    return text


SETTINGS_THEME_PALETTE_KEYS = (
    "bg",
    "panel",
    "surface",
    "field",
    "text",
    "muted",
    "accent",
    "accent2",
    "warm",
    "button",
    "select",
    "stroke",
    "glass",
)

SETTINGS_THEME_PALETTES: dict[str, dict[str, dict[str, str]]] = {
    "Flow": {
        "Dark": {
            "bg": "#061012",
            "panel": "#0b181b",
            "surface": "#111f23",
            "field": "#16272b",
            "text": "#edf7f3",
            "muted": "#93aaa5",
            "accent": "#37e2c0",
            "accent2": "#ffca68",
            "warm": "#ff4f73",
            "button": "#16282d",
            "select": "#173c39",
            "stroke": "#244648",
            "glass": "#091719",
        },
        "Light": {
            "bg": "#eef7f3",
            "panel": "#f8fffb",
            "surface": "#ffffff",
            "field": "#ffffff",
            "text": "#122420",
            "muted": "#58706a",
            "accent": "#008f7f",
            "accent2": "#b97908",
            "warm": "#c92b52",
            "button": "#dcebe6",
            "select": "#c9efe5",
            "stroke": "#abcac1",
            "glass": "#ffffff",
        },
    },
    "Roman Clay": {
        "Dark": {
            "bg": "#100d0c",
            "panel": "#191513",
            "surface": "#211c19",
            "field": "#2a2420",
            "text": "#bdb0a8",
            "muted": "#988980",
            "accent": "#e29450",
            "accent2": "#cde364",
            "warm": "#da6662",
            "button": "#2d2622",
            "select": "#473626",
            "stroke": "#4e443e",
            "glass": "#161210",
        },
        "Light": {
            "bg": "#f2f1f0",
            "panel": "#f9f8f8",
            "surface": "#fefefe",
            "field": "#fefefe",
            "text": "#5e4333",
            "muted": "#886755",
            "accent": "#8e480b",
            "accent2": "#7e9410",
            "warm": "#9c201c",
            "button": "#e7e3e1",
            "select": "#e3d9d1",
            "stroke": "#c5bcb6",
            "glass": "#fefefe",
        },
    },
    "Venetian Plaster": {
        "Dark": {
            "bg": "#100e0d",
            "panel": "#181613",
            "surface": "#201e1b",
            "field": "#282522",
            "text": "#bcb3a6",
            "muted": "#958b7d",
            "accent": "#dc7556",
            "accent2": "#dcd56a",
            "warm": "#da7e62",
            "button": "#2b2824",
            "select": "#452f28",
            "stroke": "#4c4740",
            "glass": "#151311",
        },
        "Light": {
            "bg": "#f2f1f0",
            "panel": "#f9f9f8",
            "surface": "#fefefe",
            "field": "#fefefe",
            "text": "#58462f",
            "muted": "#806a4e",
            "accent": "#882d11",
            "accent2": "#8e8615",
            "warm": "#9c3a1c",
            "button": "#e6e4e2",
            "select": "#e1d6d3",
            "stroke": "#c3bfb9",
            "glass": "#fefefe",
        },
    },
    "Lime Wash": {
        "Dark": {
            "bg": "#0e0f0d",
            "panel": "#161714",
            "surface": "#1e1f1b",
            "field": "#252723",
            "text": "#aeb8a1",
            "muted": "#869178",
            "accent": "#d4b15e",
            "accent2": "#add572",
            "warm": "#ceda62",
            "button": "#282a25",
            "select": "#433c2b",
            "stroke": "#474a42",
            "glass": "#131412",
        },
        "Light": {
            "bg": "#f1f2f0",
            "panel": "#f9f9f8",
            "surface": "#fefefe",
            "field": "#fefefe",
            "text": "#3e4e2a",
            "muted": "#617448",
            "accent": "#826217",
            "accent2": "#5c871c",
            "warm": "#8f9c1c",
            "button": "#e4e6e3",
            "select": "#e0ddd4",
            "stroke": "#bec2ba",
            "glass": "#fefefe",
        },
    },
    "Sandstone": {
        "Dark": {
            "bg": "#0f0e0d",
            "panel": "#181614",
            "surface": "#201e1b",
            "field": "#282622",
            "text": "#bbb3a5",
            "muted": "#948c7c",
            "accent": "#da6958",
            "accent2": "#dac86c",
            "warm": "#da8662",
            "button": "#2b2824",
            "select": "#452d29",
            "stroke": "#4b4841",
            "glass": "#151411",
        },
        "Light": {
            "bg": "#f2f1f0",
            "panel": "#f9f9f8",
            "surface": "#fefefe",
            "field": "#fefefe",
            "text": "#56482e",
            "muted": "#7d6b4c",
            "accent": "#872212",
            "accent2": "#8c7917",
            "warm": "#9c421c",
            "button": "#e6e5e2",
            "select": "#e1d5d3",
            "stroke": "#c3bfb9",
            "glass": "#fefefe",
        },
    },
    "Slate Quarry": {
        "Dark": {
            "bg": "#0d0e0f",
            "panel": "#141617",
            "surface": "#1c1d1f",
            "field": "#232527",
            "text": "#a9b3be",
            "muted": "#818d99",
            "accent": "#5cc2d6",
            "accent2": "#707ed7",
            "warm": "#62c2da",
            "button": "#25272a",
            "select": "#2a3f43",
            "stroke": "#434649",
            "glass": "#121314",
        },
        "Light": {
            "bg": "#f0f1f2",
            "panel": "#f8f9f9",
            "surface": "#fefefe",
            "field": "#fefefe",
            "text": "#364b63",
            "muted": "#59708b",
            "accent": "#157184",
            "accent2": "#1a2989",
            "warm": "#1c829c",
            "button": "#e3e4e5",
            "select": "#d4dee1",
            "stroke": "#bbbec1",
            "glass": "#fefefe",
        },
    },
    "Deep Forest": {
        "Dark": {
            "bg": "#0c100e",
            "panel": "#131815",
            "surface": "#1a201d",
            "field": "#212924",
            "text": "#a3baad",
            "muted": "#7a9385",
            "accent": "#bbd85a",
            "accent2": "#75d86e",
            "warm": "#62da6c",
            "button": "#242b27",
            "select": "#3e442a",
            "stroke": "#404c45",
            "glass": "#111513",
        },
        "Light": {
            "bg": "#f0f2f1",
            "panel": "#f8f9f9",
            "surface": "#fefefe",
            "field": "#fefefe",
            "text": "#2c513b",
            "muted": "#4a785d",
            "accent": "#6b8514",
            "accent2": "#208b18",
            "warm": "#1c9c26",
            "button": "#e2e6e4",
            "select": "#dee1d3",
            "stroke": "#b8c4bd",
            "glass": "#fefefe",
        },
    },
    "Oxide Copper": {
        "Dark": {
            "bg": "#0c100f",
            "panel": "#131817",
            "surface": "#1a211f",
            "field": "#212928",
            "text": "#a5bbb7",
            "muted": "#7b938f",
            "accent": "#e07c52",
            "accent2": "#e0e067",
            "warm": "#62da9a",
            "button": "#232c2a",
            "select": "#473127",
            "stroke": "#3f4d4a",
            "glass": "#111615",
        },
        "Light": {
            "bg": "#f0f2f2",
            "panel": "#f8f9f9",
            "surface": "#fefefe",
            "field": "#fefefe",
            "text": "#2c514a",
            "muted": "#49776e",
            "accent": "#8b330e",
            "accent2": "#919112",
            "warm": "#1c9c58",
            "button": "#e2e7e6",
            "select": "#e2d7d2",
            "stroke": "#b7c5c2",
            "glass": "#fefefe",
        },
    },
    "Desert Bloom": {
        "Dark": {
            "bg": "#100d0c",
            "panel": "#181413",
            "surface": "#211b1a",
            "field": "#292321",
            "text": "#bfafab",
            "muted": "#9a8682",
            "accent": "#de5482",
            "accent2": "#de9468",
            "warm": "#da6272",
            "button": "#2c2523",
            "select": "#462832",
            "stroke": "#4d423f",
            "glass": "#151211",
        },
        "Light": {
            "bg": "#f2f0f0",
            "panel": "#f9f8f8",
            "surface": "#fefefe",
            "field": "#fefefe",
            "text": "#654036",
            "muted": "#8d645a",
            "accent": "#8a0f38",
            "accent2": "#904114",
            "warm": "#9c1c2d",
            "button": "#e6e3e2",
            "select": "#e2d2d7",
            "stroke": "#c4bab8",
            "glass": "#fefefe",
        },
    },
    "Ember Glass": {
        "Dark": {
            "bg": "#130c09",
            "panel": "#1d130f",
            "surface": "#2a1b15",
            "field": "#322018",
            "text": "#fff4e8",
            "muted": "#d4ad97",
            "accent": "#ff8a52",
            "accent2": "#ffe090",
            "warm": "#15d7c0",
            "button": "#322019",
            "select": "#4a2b20",
            "stroke": "#6d3b29",
            "glass": "#190f0b",
        },
        "Light": {
            "bg": "#fff1e6",
            "panel": "#fffaf4",
            "surface": "#ffffff",
            "field": "#fffdf9",
            "text": "#2b1810",
            "muted": "#7b5d4f",
            "accent": "#b94c1e",
            "accent2": "#946108",
            "warm": "#008b7c",
            "button": "#f1d9c7",
            "select": "#ffd9c1",
            "stroke": "#d4a284",
            "glass": "#fff8ef",
        },
    },
    "Solar Ribbon": {
        "Dark": {
            "bg": "#100f07",
            "panel": "#1b190c",
            "surface": "#29240e",
            "field": "#342c12",
            "text": "#fff8df",
            "muted": "#d3bd80",
            "accent": "#ffd36f",
            "accent2": "#ff674d",
            "warm": "#28dcc3",
            "button": "#332711",
            "select": "#4b3316",
            "stroke": "#705324",
            "glass": "#171308",
        },
        "Light": {
            "bg": "#fff7df",
            "panel": "#fffdf4",
            "surface": "#ffffff",
            "field": "#fffef8",
            "text": "#2a210c",
            "muted": "#706239",
            "accent": "#9d6500",
            "accent2": "#c43a25",
            "warm": "#008b7b",
            "button": "#f2dfad",
            "select": "#ffe7aa",
            "stroke": "#d7b767",
            "glass": "#fffbe9",
        },
    },
    "Crimson Bloom": {
        "Dark": {
            "bg": "#16070e",
            "panel": "#230d16",
            "surface": "#321520",
            "field": "#3b1a28",
            "text": "#fff0f4",
            "muted": "#d8a2b0",
            "accent": "#ff466f",
            "accent2": "#ffc773",
            "warm": "#31d6c3",
            "button": "#351723",
            "select": "#511d2e",
            "stroke": "#743047",
            "glass": "#1c0a11",
        },
        "Light": {
            "bg": "#fff0f4",
            "panel": "#fff9fb",
            "surface": "#ffffff",
            "field": "#ffffff",
            "text": "#32131f",
            "muted": "#7c5260",
            "accent": "#bf2149",
            "accent2": "#a66b08",
            "warm": "#008c80",
            "button": "#f3d6df",
            "select": "#ffd7e3",
            "stroke": "#d79aac",
            "glass": "#fff7fa",
        },
    },
    "Champagne Glass": {
        "Dark": {
            "bg": "#11100b",
            "panel": "#1c1a12",
            "surface": "#29251a",
            "field": "#302c1f",
            "text": "#fff8e7",
            "muted": "#d2c199",
            "accent": "#e7c989",
            "accent2": "#fff0bc",
            "warm": "#16bfa9",
            "button": "#2f2a1c",
            "select": "#433923",
            "stroke": "#6a5b34",
            "glass": "#17150d",
        },
        "Light": {
            "bg": "#faf3df",
            "panel": "#fffaf0",
            "surface": "#ffffff",
            "field": "#fffef9",
            "text": "#282111",
            "muted": "#6e6346",
            "accent": "#967333",
            "accent2": "#806006",
            "warm": "#007f72",
            "button": "#ebe0bf",
            "select": "#f5e6bb",
            "stroke": "#cab574",
            "glass": "#fff9eb",
        },
    },
    "Teal Circuit": {
        "Dark": {
            "bg": "#021416",
            "panel": "#071f22",
            "surface": "#0e2d31",
            "field": "#12383d",
            "text": "#eafffb",
            "muted": "#91c2bc",
            "accent": "#23e7ce",
            "accent2": "#7cf7d4",
            "warm": "#ffbd6d",
            "button": "#103035",
            "select": "#104740",
            "stroke": "#1a6667",
            "glass": "#061a1d",
        },
        "Light": {
            "bg": "#e8fbf8",
            "panel": "#f5fffd",
            "surface": "#ffffff",
            "field": "#ffffff",
            "text": "#0f2928",
            "muted": "#4d706d",
            "accent": "#008b81",
            "accent2": "#168b61",
            "warm": "#b76513",
            "button": "#d2f0eb",
            "select": "#bceee5",
            "stroke": "#92cfc6",
            "glass": "#f9fffd",
        },
    },
    "Aqua Noir": {
        "Dark": {
            "bg": "#03101f",
            "panel": "#071a2e",
            "surface": "#0d2740",
            "field": "#12314d",
            "text": "#edf9ff",
            "muted": "#99bfd1",
            "accent": "#3fe8ff",
            "accent2": "#20d4aa",
            "warm": "#ff7060",
            "button": "#112d45",
            "select": "#0e4a57",
            "stroke": "#1d657b",
            "glass": "#061626",
        },
        "Light": {
            "bg": "#eaf8ff",
            "panel": "#f7fdff",
            "surface": "#ffffff",
            "field": "#ffffff",
            "text": "#102537",
            "muted": "#527284",
            "accent": "#007f96",
            "accent2": "#00896f",
            "warm": "#bf3a2d",
            "button": "#d8edf7",
            "select": "#c5f2f7",
            "stroke": "#9bc7d8",
            "glass": "#fbfeff",
        },
    },
    "Arctic Aurora": {
        "Dark": {
            "bg": "#041018",
            "panel": "#081a25",
            "surface": "#102735",
            "field": "#153241",
            "text": "#effcff",
            "muted": "#9bbdca",
            "accent": "#58f0d0",
            "accent2": "#70a8ff",
            "warm": "#d69bff",
            "button": "#122d3b",
            "select": "#174b50",
            "stroke": "#2f6372",
            "glass": "#071620",
        },
        "Light": {
            "bg": "#ecf9fb",
            "panel": "#f9feff",
            "surface": "#ffffff",
            "field": "#ffffff",
            "text": "#122b34",
            "muted": "#55727c",
            "accent": "#007f70",
            "accent2": "#3769b2",
            "warm": "#8650ad",
            "button": "#d9edf1",
            "select": "#c8eee8",
            "stroke": "#9ec8d1",
            "glass": "#fcffff",
        },
    },
    "Cobalt Heat": {
        "Dark": {
            "bg": "#070d1a",
            "panel": "#0c1729",
            "surface": "#13243b",
            "field": "#19304d",
            "text": "#f1f6ff",
            "muted": "#a1b5d0",
            "accent": "#4a91ff",
            "accent2": "#45e2c3",
            "warm": "#ff7a45",
            "button": "#172a43",
            "select": "#214577",
            "stroke": "#365f8c",
            "glass": "#0a1323",
        },
        "Light": {
            "bg": "#edf4ff",
            "panel": "#f9fbff",
            "surface": "#ffffff",
            "field": "#ffffff",
            "text": "#15243b",
            "muted": "#586c87",
            "accent": "#2464bd",
            "accent2": "#008473",
            "warm": "#c4481b",
            "button": "#dce7f6",
            "select": "#cfe0ff",
            "stroke": "#9db5d4",
            "glass": "#fcfdff",
        },
    },
    "Graphite Pulse": {
        "Dark": {
            "bg": "#0b0d12",
            "panel": "#131720",
            "surface": "#1f2632",
            "field": "#262f3d",
            "text": "#f1f5fb",
            "muted": "#a9b5c4",
            "accent": "#8ea4ff",
            "accent2": "#39d7c6",
            "warm": "#ffd067",
            "button": "#222b37",
            "select": "#26394f",
            "stroke": "#45576d",
            "glass": "#10141b",
        },
        "Light": {
            "bg": "#f0f3f7",
            "panel": "#fbfcfe",
            "surface": "#ffffff",
            "field": "#ffffff",
            "text": "#1a222e",
            "muted": "#596675",
            "accent": "#405bbb",
            "accent2": "#00877c",
            "warm": "#9b6600",
            "button": "#dfe6ee",
            "select": "#d8e5f7",
            "stroke": "#abb8c8",
            "glass": "#ffffff",
        },
    },
    "Ivory Halo": {
        "Dark": {
            "bg": "#12110d",
            "panel": "#1d1b15",
            "surface": "#2b281f",
            "field": "#342f23",
            "text": "#fffaf0",
            "muted": "#cfc4ac",
            "accent": "#d7b56d",
            "accent2": "#72d9cb",
            "warm": "#ff8666",
            "button": "#302c20",
            "select": "#3d3a26",
            "stroke": "#665d3b",
            "glass": "#181711",
        },
        "Light": {
            "bg": "#fffaf0",
            "panel": "#fffdf8",
            "surface": "#ffffff",
            "field": "#ffffff",
            "text": "#2a2417",
            "muted": "#6f644d",
            "accent": "#8a6a26",
            "accent2": "#007f76",
            "warm": "#ba482f",
            "button": "#efe6d1",
            "select": "#f3e8c7",
            "stroke": "#c9b887",
            "glass": "#fffdf7",
        },
    },
    "Midnight Ink": {
        "Dark": {
            "bg": "#0c0d10",
            "panel": "#131418",
            "surface": "#1a1b21",
            "field": "#212329",
            "text": "#abb0bf",
            "muted": "#83899c",
            "accent": "#7c51e2",
            "accent2": "#e363e3",
            "warm": "#62a6da",
            "button": "#23252c",
            "select": "#302648",
            "stroke": "#3f424d",
            "glass": "#111216",
        },
        "Light": {
            "bg": "#f0f0f2",
            "panel": "#f8f8f9",
            "surface": "#fefefe",
            "field": "#fefefe",
            "text": "#3b476d",
            "muted": "#616c92",
            "accent": "#320b8e",
            "accent2": "#950f95",
            "warm": "#1c649c",
            "button": "#e2e3e7",
            "select": "#d7d1e3",
            "stroke": "#b7bac5",
            "glass": "#fefefe",
        },
    },
    "Obsidian Gold": {
        "Dark": {
            "bg": "#100f0c",
            "panel": "#191812",
            "surface": "#222019",
            "field": "#2a2820",
            "text": "#bcb7a6",
            "muted": "#948e7c",
            "accent": "#9450e2",
            "accent2": "#e363ce",
            "warm": "#da9662",
            "button": "#2d2b22",
            "select": "#362548",
            "stroke": "#4f4b3d",
            "glass": "#161510",
        },
        "Light": {
            "bg": "#f3f2ef",
            "panel": "#f9f9f8",
            "surface": "#fefefe",
            "field": "#fefefe",
            "text": "#534a2d",
            "muted": "#796e4a",
            "accent": "#480b8e",
            "accent2": "#960d7f",
            "warm": "#9c531c",
            "button": "#e7e6e1",
            "select": "#d9d1e3",
            "stroke": "#c6c2b6",
            "glass": "#fefefe",
        },
    },
    "Violet Signal": {
        "Dark": {
            "bg": "#100b1e",
            "panel": "#1b1230",
            "surface": "#281b45",
            "field": "#312253",
            "text": "#f7f0ff",
            "muted": "#bfaee2",
            "accent": "#b88cff",
            "accent2": "#54dfff",
            "warm": "#ffcd73",
            "button": "#2a1e47",
            "select": "#3f2865",
            "stroke": "#62469a",
            "glass": "#160f29",
        },
        "Light": {
            "bg": "#f4eeff",
            "panel": "#fbf8ff",
            "surface": "#ffffff",
            "field": "#ffffff",
            "text": "#26183b",
            "muted": "#67587c",
            "accent": "#7244b8",
            "accent2": "#007d96",
            "warm": "#9b6500",
            "button": "#e5d8f7",
            "select": "#e3d2ff",
            "stroke": "#b79bdc",
            "glass": "#fdfaff",
        },
    },
    "Night City Neon": {
        "Dark": {
            "bg": "#080a12",
            "panel": "#101321",
            "surface": "#171c2d",
            "field": "#1d2338",
            "text": "#f8fbff",
            "muted": "#a9b1c8",
            "accent": "#f4ee35",
            "accent2": "#00e5ff",
            "warm": "#ff3e9d",
            "button": "#1b2032",
            "select": "#313622",
            "stroke": "#555d73",
            "glass": "#0c0f19",
        },
        "Light": {
            "bg": "#f3f4f8",
            "panel": "#ffffff",
            "surface": "#ffffff",
            "field": "#fbfcff",
            "text": "#161925",
            "muted": "#5f6578",
            "accent": "#8b8500",
            "accent2": "#007f96",
            "warm": "#bd176a",
            "button": "#e4e7ef",
            "select": "#f2efb7",
            "stroke": "#b7bdcc",
            "glass": "#ffffff",
        },
    },
    "Neon Sakura": {
        "Dark": {
            "bg": "#120a13",
            "panel": "#1c101f",
            "surface": "#29172d",
            "field": "#34203a",
            "text": "#fff4fb",
            "muted": "#d0a9c5",
            "accent": "#ff67c8",
            "accent2": "#5de5ff",
            "warm": "#c8f56b",
            "button": "#301b34",
            "select": "#51284f",
            "stroke": "#74466f",
            "glass": "#180d1a",
        },
        "Light": {
            "bg": "#fff0f8",
            "panel": "#fff9fc",
            "surface": "#ffffff",
            "field": "#ffffff",
            "text": "#31162a",
            "muted": "#79566f",
            "accent": "#b62f86",
            "accent2": "#007f98",
            "warm": "#5e8100",
            "button": "#f1d9e9",
            "select": "#ffd4ed",
            "stroke": "#d69cbe",
            "glass": "#fffafd",
        },
    },
    "Terminal Rain": {
        "Dark": {
            "bg": "#030906",
            "panel": "#07130c",
            "surface": "#0c1d12",
            "field": "#102819",
            "text": "#eaffee",
            "muted": "#8fb99a",
            "accent": "#47f57a",
            "accent2": "#adffbd",
            "warm": "#ffcd64",
            "button": "#0e2416",
            "select": "#174c29",
            "stroke": "#28663c",
            "glass": "#050f09",
        },
        "Light": {
            "bg": "#eaf7ed",
            "panel": "#f8fff9",
            "surface": "#ffffff",
            "field": "#ffffff",
            "text": "#102a18",
            "muted": "#557360",
            "accent": "#087a32",
            "accent2": "#3a8c50",
            "warm": "#9a6500",
            "button": "#d7eadb",
            "select": "#c7efd1",
            "stroke": "#9bc6a6",
            "glass": "#fbfffc",
        },
    },
    "Amber Lantern": {
        "Dark": {
            "bg": "#120e07",
            "panel": "#150f08",
            "surface": "#261b0e",
            "field": "#312313",
            "text": "#ffe0a3",
            "muted": "#a08c65",
            "accent": "#ffb000",
            "accent2": "#ffc647",
            "warm": "#f4ca7b",
            "button": "#20170c",
            "select": "#67480a",
            "stroke": "#8a6008",
            "glass": "#0b0804",
        },
        "Light": {
            "bg": "#f5f4f2",
            "panel": "#fafaf9",
            "surface": "#ffffff",
            "field": "#ffffff",
            "text": "#2d2616",
            "muted": "#706b5f",
            "accent": "#855c00",
            "accent2": "#523900",
            "warm": "#a06d0d",
            "button": "#eae8e4",
            "select": "#d3c6a9",
            "stroke": "#c8b791",
            "glass": "#ffffff",
        },
    },
    "Brass Lamp": {
        "Dark": {
            "bg": "#1a1410",
            "panel": "#1f1811",
            "surface": "#2e2319",
            "field": "#382b1f",
            "text": "#f2e8dc",
            "muted": "#9f978e",
            "accent": "#d9a441",
            "accent2": "#e5c07c",
            "warm": "#f4ca7b",
            "button": "#292016",
            "select": "#614a25",
            "stroke": "#7d5e2b",
            "glass": "#140f0c",
        },
        "Light": {
            "bg": "#f5f4f2",
            "panel": "#fafaf9",
            "surface": "#ffffff",
            "field": "#ffffff",
            "text": "#2d2516",
            "muted": "#736d63",
            "accent": "#85601b",
            "accent2": "#5b4112",
            "warm": "#a06d0d",
            "button": "#eae8e4",
            "select": "#d3c8b2",
            "stroke": "#c8b99c",
            "glass": "#ffffff",
        },
    },
    "Fire Opal": {
        "Dark": {
            "bg": "#140503",
            "panel": "#1b0705",
            "surface": "#2e0c09",
            "field": "#3b0f0b",
            "text": "#ffe7d6",
            "muted": "#99857b",
            "accent": "#ff8b50",
            "accent2": "#ffba97",
            "warm": "#f4ca7b",
            "button": "#280a07",
            "select": "#6d321e",
            "stroke": "#8e462a",
            "glass": "#0b0302",
        },
        "Light": {
            "bg": "#f5f3f2",
            "panel": "#fafaf9",
            "surface": "#ffffff",
            "field": "#ffffff",
            "text": "#2d1d16",
            "muted": "#766b67",
            "accent": "#d54800",
            "accent2": "#a23700",
            "warm": "#a06d0d",
            "button": "#eae6e4",
            "select": "#ebc0a9",
            "stroke": "#e8af91",
            "glass": "#ffffff",
        },
    },
    "Sunset Coast": {
        "Dark": {
            "bg": "#26140b",
            "panel": "#21110a",
            "surface": "#331a0f",
            "field": "#3e2013",
            "text": "#ffe9d2",
            "muted": "#a18d7c",
            "accent": "#ffb347",
            "accent2": "#ffd08e",
            "warm": "#f4ca7b",
            "button": "#2d170e",
            "select": "#704820",
            "stroke": "#916029",
            "glass": "#1e1009",
        },
        "Light": {
            "bg": "#f5f4f2",
            "panel": "#fafaf9",
            "surface": "#ffffff",
            "field": "#ffffff",
            "text": "#2d2316",
            "muted": "#736c63",
            "accent": "#b86c00",
            "accent2": "#854e00",
            "warm": "#a06d0d",
            "button": "#eae8e4",
            "select": "#e3cba9",
            "stroke": "#ddbe91",
            "glass": "#ffffff",
        },
    },
    "Rust Belt": {
        "Dark": {
            "bg": "#1c0f09",
            "panel": "#1f110a",
            "surface": "#301b10",
            "field": "#3c2113",
            "text": "#f7e3d5",
            "muted": "#9f8e83",
            "accent": "#ff7a45",
            "accent2": "#ffad8c",
            "warm": "#f4ca7b",
            "button": "#2b170e",
            "select": "#6e3820",
            "stroke": "#8f4728",
            "glass": "#140b07",
        },
        "Light": {
            "bg": "#f5f3f2",
            "panel": "#fafaf9",
            "surface": "#ffffff",
            "field": "#ffffff",
            "text": "#2d1c16",
            "muted": "#766b67",
            "accent": "#ca3900",
            "accent2": "#972b00",
            "warm": "#a06d0d",
            "button": "#eae6e4",
            "select": "#e8bba9",
            "stroke": "#e4a991",
            "glass": "#ffffff",
        },
    },
    "Bone China": {
        "Dark": {
            "bg": "#080705",
            "panel": "#322712",
            "surface": "#433418",
            "field": "#463719",
            "text": "#e4e1dd",
            "muted": "#a9a7a3",
            "accent": "#b17337",
            "accent2": "#ce9761",
            "warm": "#f4ca7b",
            "button": "#3d3016",
            "select": "#644721",
            "stroke": "#765126",
            "glass": "#020201",
        },
        "Light": {
            "bg": "#e9e4da",
            "panel": "#faf7f1",
            "surface": "#ffffff",
            "field": "#ffffff",
            "text": "#2e2a24",
            "muted": "#66625b",
            "accent": "#8a5a2b",
            "accent2": "#63411f",
            "warm": "#a06d0d",
            "button": "#dfd8ca",
            "select": "#ccbba6",
            "stroke": "#c3ad94",
            "glass": "#fdfbf9",
        },
    },
    "Paper Press": {
        "Dark": {
            "bg": "#130f09",
            "panel": "#271f0f",
            "surface": "#382c15",
            "field": "#43351a",
            "text": "#e1deda",
            "muted": "#a7a39f",
            "accent": "#db5429",
            "accent2": "#e58566",
            "warm": "#f4ca7b",
            "button": "#322813",
            "select": "#69381b",
            "stroke": "#833e1e",
            "glass": "#0c0a06",
        },
        "Light": {
            "bg": "#f1ebe1",
            "panel": "#f6f1e8",
            "surface": "#ffffff",
            "field": "#ffffff",
            "text": "#2a2622",
            "muted": "#6c6862",
            "accent": "#b3421e",
            "accent2": "#873217",
            "warm": "#a06d0d",
            "button": "#e9dfd0",
            "select": "#deb8a6",
            "stroke": "#d8a793",
            "glass": "#f9f5ef",
        },
    },
    "Moss Stone": {
        "Dark": {
            "bg": "#0f1611",
            "panel": "#111a13",
            "surface": "#1a281d",
            "field": "#203124",
            "text": "#e6f2e2",
            "muted": "#909a8e",
            "accent": "#a8e05f",
            "accent2": "#c9ec9b",
            "warm": "#f4ca7b",
            "button": "#17231a",
            "select": "#455f31",
            "stroke": "#5b7d3b",
            "glass": "#0b100c",
        },
        "Light": {
            "bg": "#f4f5f2",
            "panel": "#fafaf9",
            "surface": "#ffffff",
            "field": "#ffffff",
            "text": "#232d16",
            "muted": "#69705f",
            "accent": "#598a1a",
            "accent2": "#3d5f12",
            "warm": "#a06d0d",
            "button": "#e8eae4",
            "select": "#c6d5b1",
            "stroke": "#b6ca9c",
            "glass": "#ffffff",
        },
    },
    "Olive Grove": {
        "Dark": {
            "bg": "#2b2f1e",
            "panel": "#252919",
            "surface": "#323722",
            "field": "#343b23",
            "text": "#eef0dc",
            "muted": "#a3a693",
            "accent": "#dcc78d",
            "accent2": "#ede2c4",
            "warm": "#f4ca7b",
            "button": "#2e331f",
            "select": "#5e5c3e",
            "stroke": "#807953",
            "glass": "#25291a",
        },
        "Light": {
            "bg": "#f5f4f2",
            "panel": "#fafaf9",
            "surface": "#ffffff",
            "field": "#ffffff",
            "text": "#2d2716",
            "muted": "#706b5f",
            "accent": "#977d30",
            "accent2": "#705d24",
            "warm": "#a06d0d",
            "button": "#eae8e4",
            "select": "#d9d0b8",
            "stroke": "#cfc4a4",
            "glass": "#ffffff",
        },
    },
    "Jade Garden": {
        "Dark": {
            "bg": "#060706",
            "panel": "#1b281b",
            "surface": "#243624",
            "field": "#2a3f2a",
            "text": "#dbe6e1",
            "muted": "#9fa7a3",
            "accent": "#3da27a",
            "accent2": "#62c49d",
            "warm": "#f4ca7b",
            "button": "#213121",
            "select": "#2c563e",
            "stroke": "#30684c",
            "glass": "#010201",
        },
        "Light": {
            "bg": "#dfe5e0",
            "panel": "#f3f7f3",
            "surface": "#ffffff",
            "field": "#ffffff",
            "text": "#22302a",
            "muted": "#5b6661",
            "accent": "#2f7d5e",
            "accent2": "#215842",
            "warm": "#a06d0d",
            "button": "#d1dad2",
            "select": "#aac6b9",
            "stroke": "#99bbac",
            "glass": "#f9fbf9",
        },
    },
    "Rose Quartz": {
        "Dark": {
            "bg": "#160a09",
            "panel": "#2c130f",
            "surface": "#3d1a15",
            "field": "#491f19",
            "text": "#ede5e4",
            "muted": "#9e9594",
            "accent": "#c8948d",
            "accent2": "#dfc1bd",
            "warm": "#f4ca7b",
            "button": "#371813",
            "select": "#673f39",
            "stroke": "#7d524c",
            "glass": "#0f0706",
        },
        "Light": {
            "bg": "#f3e4e2",
            "panel": "#f8ecea",
            "surface": "#ffffff",
            "field": "#ffffff",
            "text": "#3a2a28",
            "muted": "#726260",
            "accent": "#aa5d50",
            "accent2": "#874a40",
            "warm": "#a06d0d",
            "button": "#ecd3d0",
            "select": "#ddbcb6",
            "stroke": "#d6aea8",
            "glass": "#fbf3f2",
        },
    },
    "Emerald Vault": {
        "Dark": {
            "bg": "#041710",
            "panel": "#08211a",
            "surface": "#0c3329",
            "field": "#0f4032",
            "text": "#ddefe3",
            "muted": "#98aba0",
            "accent": "#daaa2b",
            "accent2": "#e5c268",
            "warm": "#f4ca7b",
            "button": "#0b2d24",
            "select": "#4a572a",
            "stroke": "#6b6a2a",
            "glass": "#020e0a",
        },
        "Light": {
            "bg": "#f5f4f2",
            "panel": "#fafaf9",
            "surface": "#ffffff",
            "field": "#ffffff",
            "text": "#2d2616",
            "muted": "#706b5f",
            "accent": "#765b15",
            "accent2": "#4b3a0d",
            "warm": "#a06d0d",
            "button": "#eae8e4",
            "select": "#cfc6b0",
            "stroke": "#c2b79a",
            "glass": "#ffffff",
        },
    },
    "Neon Wire": {
        "Dark": {
            "bg": "#08080d",
            "panel": "#0b0b12",
            "surface": "#141420",
            "field": "#1a1a2a",
            "text": "#e6fbff",
            "muted": "#7e8a8e",
            "accent": "#fcee0a",
            "accent2": "#fdf351",
            "warm": "#f4ca7b",
            "button": "#11111b",
            "select": "#5a5519",
            "stroke": "#7f7816",
            "glass": "#040407",
        },
        "Light": {
            "bg": "#f5f5f2",
            "panel": "#fafaf9",
            "surface": "#ffffff",
            "field": "#ffffff",
            "text": "#2d2b16",
            "muted": "#706e5f",
            "accent": "#8a8202",
            "accent2": "#585301",
            "warm": "#a06d0d",
            "button": "#eaeae4",
            "select": "#d5d2aa",
            "stroke": "#cac792",
            "glass": "#ffffff",
        },
    },
    "Ultraviolet Hour": {
        "Dark": {
            "bg": "#140a24",
            "panel": "#190e2c",
            "surface": "#23143d",
            "field": "#291749",
            "text": "#f0e7ff",
            "muted": "#9187a0",
            "accent": "#d092ff",
            "accent2": "#efd9ff",
            "warm": "#f4ca7b",
            "button": "#201238",
            "select": "#573a77",
            "stroke": "#734e96",
            "glass": "#10081c",
        },
        "Light": {
            "bg": "#f4f2f5",
            "panel": "#faf9fa",
            "surface": "#ffffff",
            "field": "#ffffff",
            "text": "#23162d",
            "muted": "#736a7a",
            "accent": "#9b18ff",
            "accent2": "#8100e4",
            "warm": "#a06d0d",
            "button": "#e8e4ea",
            "select": "#d9b1f8",
            "stroke": "#d09bf9",
            "glass": "#ffffff",
        },
    },
    "Plum Velvet": {
        "Dark": {
            "bg": "#1a0f1c",
            "panel": "#1d1120",
            "surface": "#2b192f",
            "field": "#341e39",
            "text": "#f6e7f4",
            "muted": "#9a8d9a",
            "accent": "#c792ff",
            "accent2": "#ecd9ff",
            "warm": "#f4ca7b",
            "button": "#26162a",
            "select": "#5a3d6d",
            "stroke": "#73518f",
            "glass": "#140b15",
        },
        "Light": {
            "bg": "#f3f2f5",
            "panel": "#faf9fa",
            "surface": "#ffffff",
            "field": "#ffffff",
            "text": "#21162d",
            "muted": "#726a7a",
            "accent": "#8818ff",
            "accent2": "#6f00e4",
            "warm": "#a06d0d",
            "button": "#e6e4ea",
            "select": "#d3b1f8",
            "stroke": "#c89bf9",
            "glass": "#ffffff",
        },
    },
}


# ---------------------------------------------------------------------------
# X-337: the material layer. His order on the gallery: "each of them need to
# be the ACTUAL color... with the text being the most appropriate text color."
# The X-145 bars used the bg token, and every dark bg is within a few RGB
# points of black -- twenty-five materials rendered as identical black bars.
# The material is composed from the theme's own chromatic tokens (select
# tinted toward accent), so Roman Clay reads as clay and Flow reads as teal
# while every hex still comes from that theme's palette.

def blend_hex(base: str, tint: str, amount: float) -> str:
    """Mix ``tint`` into ``base`` by ``amount`` (0..1), returning hex."""
    b = base.lstrip("#")
    t = tint.lstrip("#")
    mixed = "".join(
        f"{round(int(b[i:i + 2], 16) * (1 - amount) + int(t[i:i + 2], 16) * amount):02x}"
        for i in (0, 2, 4)
    )
    return "#" + mixed


def _linear(channel: float) -> float:
    channel /= 255.0
    return channel / 12.92 if channel <= 0.04045 * 255 / 255 else ((channel + 0.055) / 1.055) ** 2.4


def relative_luminance(colour: str) -> float:
    h = colour.lstrip("#")
    r, g, b = (int(h[i:i + 2], 16) for i in (0, 2, 4))
    return 0.2126 * _linear(r) + 0.7152 * _linear(g) + 0.0722 * _linear(b)


def contrast_ratio(a: str, b: str) -> float:
    la, lb = relative_luminance(a), relative_luminance(b)
    lighter, darker = max(la, lb), min(la, lb)
    return (lighter + 0.05) / (darker + 0.05)


def theme_material(palette: dict[str, str], mode: str) -> str:
    """The row colour that reads as the theme's material, from its own tokens."""
    amount = 0.16 if mode == "Dark" else 0.10
    return blend_hex(palette["select"], palette["accent"], amount)


def material_grain(material: str, mode: str) -> str:
    """The stipple overlay that gives the material its tooth."""
    toward = "#ffffff" if mode == "Dark" else "#000000"
    return blend_hex(material, toward, 0.09)


def material_ink(palette: dict[str, str], material: str) -> str:
    """The most readable of the theme's own inks on this material, with a
    guaranteed-legible neutral as the last resort."""
    candidates = (palette["text"], palette["bg"], "#f5f2ee", "#141210")
    for candidate in candidates:
        if contrast_ratio(candidate, material) >= 4.5:
            return candidate
    return max(candidates, key=lambda candidate: contrast_ratio(candidate, material))
